# IMPORTANT (if using mise + vscode):
# To allow vscode to see this file, you can symlink this to mise.local.toml in the root directory. From this aemu-bazel directory, run:
# > ln -sf third_party/mesa3d/aemu-bazel/mise.toml ../../../mise.local.toml
[env]
# The root of our bazel workspace
BAZEL_ROOT = "{{config_root}}"
'_'.path = [
    "{{config_root}}/prebuilts/bazel/{% if os() == 'linux' %}linux-x86_64{% elif os() == 'macos' %}darwin-x86_64{% else %}windows-x86_64{% endif %}",
    "{{config_root}}/prebuilts/clang/host/{% if os() == 'linux' %}linux-x86{% elif os() == 'macos' %}darwin-x86{% else %}windows-x86{% endif %}/{{ exec(command='jq -r .clang build/bazel/toolchains/tool_versions.json') }}/bin",
    "$ANDROID_HOME/platform-tools/"
]
# DISPLAY = ":0"
# VULKAN_SDK = "<path-to-your-vulkan-sdk>"

############ BEGIN bazel commands ######################

[tasks.bazel-clean]
description = "Runs bazel clean --expunge"
run = "cd $BAZEL_ROOT && bazel clean --expunge"

[tasks.upload_fishtank]
description = "Runs upload_fishtank (Run `~/go/bin/oauth2l reset` beforehand"
run = "~/go/bin/oauth2l reset; cd $BAZEL_ROOT && bazel run //hardware/generic/goldfish/emulator/tools/upload_fishtank:upload_fishtank -- -v 15253823"

[tasks.test-release_zip_test]
description = "Runs release_zip_test"
run = "cd $BAZEL_ROOT && bazel test @goldfish//emulator/tests:release_zip_test"
############ END bazel commands ######################

############ BEGIN mesa/lavapipe commands ######################

[tasks.build-lavapipe-amc-meson]
description = "Build libvulkan_lvp.so using meson + amc-generated toolchain"
run = "cd $BAZEL_ROOT/third_party/mesa3d/aemu-bazel && python3 amc_meson_build.py --build-config aemu-mesa3d-build-config.jsonc --install-dir $BAZEL_ROOT/prebuilts/android-emulator-build/common/vulkan/linux-x86_64/icds .. 2>&1 | tee test-amc-meson.log"

[tasks.gen-bazel-files-lavapipe]
description = "Generates the bazel build files for building lavapipe."
run = "cd $BAZEL_ROOT/third_party/mesa3d/aemu-bazel && python3 amc_meson_build.py --build-config aemu-mesa3d-build-config.jsonc --shim aemu-mesa3d-shim.jsonc --gen-bazel .. 2>&1 | tee gen-bazel-lavapipe.log"

[tasks.run-vulkaninfo-lavapipe]
description = "Run vulkaninfo from the vulkan sdk against the lavapipe library."
env  = { VK_DRIVER_FILES = "./lvp_icd.json" }
run = "cd $BAZEL_ROOT/prebuilts/android-emulator-build/common/vulkan/linux-x86_64/icds && $VULKAN_SDK/x86_64/bin/vulkaninfo"

# TODO: This should be a part of amc_meson_build.py
[tasks.copy-lavapipe-deps-prebuilts]
description = "Copy libvulkan_lvp.so deps to prebuilts"
run = "cd $BAZEL_ROOT/prebuilts/android-emulator-build/common/vulkan/linux-x86_64/icds && cp $BAZEL_ROOT/bazel-out/k8-fastbuild/bin/external/libxcb+/libxcb-aemu.so . && ./update_runpath.sh"

####### END mesa/lavapipe commands ######################

############ BEGIN bazel gen commands ######################

[tasks.gen-bazel-libdrm]
description = "Generate bazel files for libdrm"
run = "cd $BAZEL_ROOT/third_party/libdrm && aemu-bazel/generate_bazel_files.sh"

[tasks.gen-bazel-wayland]
description = "Generate bazel files for wayland"
run = "cd $BAZEL_ROOT/third_party/wayland && aemu-bazel/generate_bazel_files.sh"

############ END bazel gen commands ######################